---
- hosts: gfg
  become: yes
  vars:
    currstate: present
  tasks:
    - name: Install HTOP
      action: yum name=htop state='{{currstate}}'
    - name: Install Git
      action: yum name=git state='{{currstate}}'
