---
- hosts: gfg
  become: yes
  vars:
    currstate: absent

  tasks:
    - name: Remove HTOP
      action: yum name=htop state='{{ currstate }}'

    - name: Remove Git
      action: tum name=git state='{{ currstate }}'

    - name: Autoremove unused packages
      action: yum autoremove=yes
